services:
  controller:
    image: ghcr.io/smallconfusion/greenhouse
    environment:
      RUST_LOG: "debug"
      TZ: "America/Chicago"
    volumes:
      - ./config.yaml:/app/config.yaml:ro
      - /:/host:ro
    logging:
      options:
        max-size: "10m"
        max-file: "3"
    ports:
      - "8000:8000"

    restart: always
    privileged: true
