# yaml-language-server: $schema=config.schema.json

temperature_path: "/host/sys/bus/w1/devices/28-000000baf13f/temperature"

controller_desc:
  peripherals:
    heater: [11, Off]

    fan1: [14, Off]
    fan2: [15, Off]

    main_vent:
      - on: 12
        off: 13
      - 0.0

  stage_sets:
    - name: "Main Set"
      stages:
        - name: "Heating"
          condition:
            type: TempRange
            start: -999.0
            end: 58.0
          exit_condition:
            type: TempRange
            start: -999.0
            end: 60.0
          settings:
            heater: On

        - name: "Cooling 1"
          condition:
            type: TempRange
            start: 76.0
            end: 78.0
          exit_condition:
            type: TempRange
            start: 74.0
            end: 78.0
          settings:
            main_vent: 30.0

        - name: "Cooling 2"
          condition:
            type: TempRange
            start: 78.0
            end: 80.0
          exit_condition:
            type: TempRange
            start: 76.0
            end: 80.0
          settings:
            main_vent: 60.0
            fan1: On

        - name: "Cooling 3"
          condition:
            type: TempRange
            start: 80.0
            end: 999.0
          exit_condition:
            type: TempRange
            start: 78.0
            end: 999.0
          settings:
            fan1: On
            fan2: On
            main_vent: 120.0
